---
db_address: 127.0.0.1
auth_code_life_time: 1m
id_token_life_time: 30d
access_token_life_time: 30d
email_verified: "https://example.com"
confirm_email: "https://example.com/auth/confirm-email/"
login: "https://example.com/signin"
signup_complete: "https://example.com/signup-complete"
reset_password_api_endpoint: "http://example.com:9000/api/v2/users/password_reset"
---
